service: fd-worker
frameworkVersion: '3'
useDotenv: true
provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  profile: default

#  environment:
#    variable1: value1

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  register_user:
    handler: bin/register_user
    events:
      - cognitoUserPool:
          pool: folio-driven-dev
          trigger: PostConfirmation
          existing: true
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_PORT: ${env:DB_PORT}
      DB_NAME: ${env:DB_NAME}
      DB_USER: ${env:DB_USER}
      DB_PASS: ${env:DB_PASS}
