version: "3"

services:
  mysql:
    image: mysql:8
    platform: linux/arm64
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    volumes:
      - ./.db:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
